[package]
publish = false
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
xjbutil = { version = "0.9.0-ECHO", default-features = false, features = ["minhttpd"] }
log = "0.4"
env_logger = "0.10"