name: build

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build-backstage:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: [18.x, 20.x]
    steps:
      - name: Set git to use LF (WINDOWS L)
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
        if: runner.os == 'Windows'
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        working-directory: ./backstage
        run: |
          npm install
      - working-directory: ./backstage
        run: |
          npm ci
      - name: Backstage test scripts
        working-directory: ./backstage
        run: npm run test --if-present
      - name: Build backstage
        working-directory: ./backstage
        run: npm run release_build --if-present
      - name: Run ESLint for backstage
        working-directory: ./backstage
        run: npm run lint
